# Generated by Django 5.0.1 on 2024-01-24 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="キャンプ場名")),
                ("location", models.CharField(max_length=255, verbose_name="場所")),
                ("description", models.TextField(verbose_name="説明")),
                ("amenities", models.JSONField(verbose_name="アメニティ")),
                ("image", models.ImageField(upload_to="campsites/", verbose_name="画像")),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("end_date", models.DateField(verbose_name="終了日")),
                ("num_people", models.IntegerField(verbose_name="人数")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "campsite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="blog.campsite",
                        verbose_name="キャンプ場",
                    ),
                ),
            ],
        ),
    ]
