# Generated by Django 5.0.1 on 2024-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_campsite_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="campsite",
            name="access_info",
            field=models.TextField(blank=True, verbose_name="アクセス情報"),
        ),
        migrations.AddField(
            model_name="campsite",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
        ),
        migrations.AddField(
            model_name="campsite",
            name="price",
            field=models.CharField(blank=True, max_length=255, verbose_name="料金"),
        ),
        migrations.AlterField(
            model_name="campsite",
            name="amenities",
            field=models.JSONField(verbose_name="設備"),
        ),
        migrations.AlterField(
            model_name="campsite",
            name="description",
            field=models.TextField(verbose_name="キャンプ場の説明"),
        ),
    ]
