# Generated by Django 5.0.1 on 2024-02-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_campsite_access_info_campsite_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="エリア名")),
                ("area_code", models.CharField(max_length=6, verbose_name="エリアコード")),
            ],
        ),
    ]
