# Generated by Django 5.0.1 on 2024-02-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_weatherarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="campsite",
            name="weather_area",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="天気予報エリアコード"
            ),
        ),
    ]
